tasks:

  build:
    cmds:
      - fish -c 'for boat in boats/*; echo Fishing $boat …; fisher $boat; end'
      - fish -c 'fisher up'

  rebuild:
    cmds:
      - git clean -xd -f
      - task: build
      - git checkout fishd.*
  
  test:
    cmds:
      - fish -c 'fishtape **.test.fish | tap-colorize'

output: 'prefixed'
version: '2'
