tasks:

  rebuild:
    cmds:
      # uninstall and clean should not run in parallel
      # b/c uninstall dramatically reduces the need for cleaning
      - task: uninstall-all-plugins
      - task: clean
      - task: build

  build:
    cmds:
      - fish -c 'fisher plugins/*'

  uninstall-all-plugins:
    cmds:
      - fish -c 'fisher ls | fisher rm'

  clean:
    cmds:
      - git clean -xd -f

  test:
    cmds:
      - fish -c 'fishtape **.test.fish | tap-colorize'

output: 'prefixed'
version: '2'
