tasks:

  build:
    cmds:
      - fish -c 'for boat in boats/*; echo Fishing $boat …; fisher $boat; end'
      - fish -c 'fisher up'

  rebuild:
    cmds:
      - task: clean
      - task: build
  
  clean:
    cmds:
      - git clean -xd -f

  test:
    cmds:
      - fish -c 'fishtape **.test.fish | tap-colorize'

output: 'prefixed'
version: '2'
