tasks:

  build:
    cmds:
      - fish -c 'fisher boats/*'
      - fish -c 'fisher up'

  rebuild:
    cmds:
      - task: clean
      - task: build
  
  rebuild-from-scratch:
    cmds:
      - task: uninstall-all-plugins
      - task: rebuild

  uninstall-all-plugins:
    cmds:
      - fish -c 'fisher ls | fisher rm'

  clean:
    cmds:
      - git clean -xd -f

  test:
    cmds:
      - fish -c 'fishtape **.test.fish | tap-colorize'

output: 'prefixed'
version: '2'
