tasks:

  build:
    cmds:
      - fish -c 'for boat in boats/*; echo Fishing $boat …; fisher $boat; end'
      - fish -c 'fisher up'

  rebuild:
    cmds:
      - git clean -xd -f
      - task: build
      - git checkout .

output: 'prefixed'
version: '2'
