tasks:
  default:
    deps: [rebuild]

  rebuild:
    cmds:
      - task: clean
      - task: build
      - task: test

  build:
    cmds:
      - fish -c 'fisher add ./plugins/*'

  clean:
    cmds:
      - git clean -Xd -f

  test:
    cmds:
      - fish -c 'fishtape **.test.fish | tap-colorize'

output: 'prefixed'
version: '2'
